#! /bin/bash
#
# \Author   Hans Kramer
#
# \Date     July 2016
#


download() {
    rm -f $filename
    wget $URL
}


unpack() {
    #rm -rf work/*
    BASEPATH=$TYPE/$NAME-$VERSION
    mkdir -p ${BASEPATH}/DEBIAN
    mkdir -p ${BASEPATH}/usr/share/themes/
    tar -C ${BASEPATH}/usr/share/themes/ -xf $filename
    cat <<-EOF > ${BASEPATH}/DEBIAN/control
	Package: metacity-theme-$NAME
	Version: $VERSION
	Architecture: all
	Essential: no
	Section: gnome
	Priority: optional
	Depends: metacity
	Maintainer: Hans Kramer
	Description: Metacity Themes collected by Hans Kramer
	EOF
}


create_pkg() {
    cd $TYPE
    dpkg --build $NAME-$VERSION    
}


#theme_config=Gnomesmite
theme_config=$1

source $theme_config

filename=$(basename $URL)

download

unpack

create_pkg
